services:
  - type: web
    name: altavellum
    env: python
    build:
      runtime: python-3.11.9
      buildCommand: |
        pip install -r requirements.txt
        python manage.py collectstatic --noinput
    startCommand: gunicorn harmo.wsgi
    autoDeploy: true