services:
  - type: web
    name: altavellum
    env: python
    build:
      runtime: python-3.10
      buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn harmo.wsgi"
    autoDeploy: true
