services:
  - type: web
    name: altavellum
    env: python
    runtime: python-3.11.9
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn harmo.wsgi:application
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: harmo.settings
